// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/contacts.proto

package com.power.proto3;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string home_address = 1;</code>
   * @return The homeAddress.
   */
  java.lang.String getHomeAddress();
  /**
   * <code>string home_address = 1;</code>
   * @return The bytes for homeAddress.
   */
  com.google.protobuf.ByteString
      getHomeAddressBytes();

  /**
   * <code>string unit_address = 2;</code>
   * @return The unitAddress.
   */
  java.lang.String getUnitAddress();
  /**
   * <code>string unit_address = 2;</code>
   * @return The bytes for unitAddress.
   */
  com.google.protobuf.ByteString
      getUnitAddressBytes();
}
