// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/contacts.proto

package com.power.proto3;

public interface ContactsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.Contacts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  java.util.List<com.power.proto3.PeopleInfo> 
      getContactsList();
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  com.power.proto3.PeopleInfo getContacts(int index);
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  int getContactsCount();
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  java.util.List<? extends com.power.proto3.PeopleInfoOrBuilder> 
      getContactsOrBuilderList();
  /**
   * <code>repeated .proto3.PeopleInfo contacts = 1;</code>
   */
  com.power.proto3.PeopleInfoOrBuilder getContactsOrBuilder(
      int index);
}
