// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/contacts.proto

package com.power.proto3;

/**
 * Protobuf type {@code proto3.PeopleInfo}
 */
public final class PeopleInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto3.PeopleInfo)
    PeopleInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PeopleInfo.newBuilder() to construct.
  private PeopleInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PeopleInfo() {
    name_ = "";
    phone_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PeopleInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.power.proto3.PeopleInfo.class, com.power.proto3.PeopleInfo.Builder.class);
  }

  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto3.PeopleInfo.Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
     * @return The type.
     */
    com.power.proto3.PeopleInfo.Phone.PhoneType getType();
  }
  /**
   * Protobuf type {@code proto3.PeopleInfo.Phone}
   */
  public static final class Phone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto3.PeopleInfo.Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Phone();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.power.proto3.PeopleInfo.Phone.class, com.power.proto3.PeopleInfo.Phone.Builder.class);
    }

    /**
     * <pre>
     * 0值必须存在，且作为第一个枚举常量的值
     * 枚举值范围：32位整数范围，不要设置负数
     * </pre>
     *
     * Protobuf enum {@code proto3.PeopleInfo.Phone.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 移动电话
       * </pre>
       *
       * <code>MP = 0;</code>
       */
      MP(0),
      /**
       * <pre>
       * 固定电话
       * </pre>
       *
       * <code>TEL = 1;</code>
       */
      TEL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 移动电话
       * </pre>
       *
       * <code>MP = 0;</code>
       */
      public static final int MP_VALUE = 0;
      /**
       * <pre>
       * 固定电话
       * </pre>
       *
       * <code>TEL = 1;</code>
       */
      public static final int TEL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return MP;
          case 1: return TEL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.power.proto3.PeopleInfo.Phone.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto3.PeopleInfo.Phone.PhoneType)
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object number_ = "";
    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public com.power.proto3.PeopleInfo.Phone.PhoneType getType() {
      com.power.proto3.PeopleInfo.Phone.PhoneType result = com.power.proto3.PeopleInfo.Phone.PhoneType.forNumber(type_);
      return result == null ? com.power.proto3.PeopleInfo.Phone.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (type_ != com.power.proto3.PeopleInfo.Phone.PhoneType.MP.getNumber()) {
        output.writeEnum(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (type_ != com.power.proto3.PeopleInfo.Phone.PhoneType.MP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.power.proto3.PeopleInfo.Phone)) {
        return super.equals(obj);
      }
      com.power.proto3.PeopleInfo.Phone other = (com.power.proto3.PeopleInfo.Phone) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.power.proto3.PeopleInfo.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.power.proto3.PeopleInfo.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.power.proto3.PeopleInfo.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.power.proto3.PeopleInfo.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto3.PeopleInfo.Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto3.PeopleInfo.Phone)
        com.power.proto3.PeopleInfo.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.power.proto3.PeopleInfo.Phone.class, com.power.proto3.PeopleInfo.Phone.Builder.class);
      }

      // Construct using com.power.proto3.PeopleInfo.Phone.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        number_ = "";
        type_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_Phone_descriptor;
      }

      @java.lang.Override
      public com.power.proto3.PeopleInfo.Phone getDefaultInstanceForType() {
        return com.power.proto3.PeopleInfo.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public com.power.proto3.PeopleInfo.Phone build() {
        com.power.proto3.PeopleInfo.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.power.proto3.PeopleInfo.Phone buildPartial() {
        com.power.proto3.PeopleInfo.Phone result = new com.power.proto3.PeopleInfo.Phone(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.power.proto3.PeopleInfo.Phone result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.number_ = number_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.power.proto3.PeopleInfo.Phone) {
          return mergeFrom((com.power.proto3.PeopleInfo.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.power.proto3.PeopleInfo.Phone other) {
        if (other == com.power.proto3.PeopleInfo.Phone.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                number_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        number_ = getDefaultInstance().getNumber();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.power.proto3.PeopleInfo.Phone.PhoneType getType() {
        com.power.proto3.PeopleInfo.Phone.PhoneType result = com.power.proto3.PeopleInfo.Phone.PhoneType.forNumber(type_);
        return result == null ? com.power.proto3.PeopleInfo.Phone.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.power.proto3.PeopleInfo.Phone.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto3.PeopleInfo.Phone.PhoneType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto3.PeopleInfo.Phone)
    }

    // @@protoc_insertion_point(class_scope:proto3.PeopleInfo.Phone)
    private static final com.power.proto3.PeopleInfo.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.power.proto3.PeopleInfo.Phone();
    }

    public static com.power.proto3.PeopleInfo.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.power.proto3.PeopleInfo.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_ = 0;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }

  public static final int PHONE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.power.proto3.PeopleInfo.Phone> phone_;
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.power.proto3.PeopleInfo.Phone> getPhoneList() {
    return phone_;
  }
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.power.proto3.PeopleInfo.PhoneOrBuilder> 
      getPhoneOrBuilderList() {
    return phone_;
  }
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  @java.lang.Override
  public int getPhoneCount() {
    return phone_.size();
  }
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  @java.lang.Override
  public com.power.proto3.PeopleInfo.Phone getPhone(int index) {
    return phone_.get(index);
  }
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  @java.lang.Override
  public com.power.proto3.PeopleInfo.PhoneOrBuilder getPhoneOrBuilder(
      int index) {
    return phone_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    for (int i = 0; i < phone_.size(); i++) {
      output.writeMessage(3, phone_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    for (int i = 0; i < phone_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, phone_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.power.proto3.PeopleInfo)) {
      return super.equals(obj);
    }
    com.power.proto3.PeopleInfo other = (com.power.proto3.PeopleInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getAge()
        != other.getAge()) return false;
    if (!getPhoneList()
        .equals(other.getPhoneList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    if (getPhoneCount() > 0) {
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.power.proto3.PeopleInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.proto3.PeopleInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.proto3.PeopleInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.proto3.PeopleInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.proto3.PeopleInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.proto3.PeopleInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.proto3.PeopleInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.power.proto3.PeopleInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.power.proto3.PeopleInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.power.proto3.PeopleInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.power.proto3.PeopleInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.power.proto3.PeopleInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.power.proto3.PeopleInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto3.PeopleInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto3.PeopleInfo)
      com.power.proto3.PeopleInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.power.proto3.PeopleInfo.class, com.power.proto3.PeopleInfo.Builder.class);
    }

    // Construct using com.power.proto3.PeopleInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      age_ = 0;
      if (phoneBuilder_ == null) {
        phone_ = java.util.Collections.emptyList();
      } else {
        phone_ = null;
        phoneBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.power.proto3.ContactsProtos.internal_static_proto3_PeopleInfo_descriptor;
    }

    @java.lang.Override
    public com.power.proto3.PeopleInfo getDefaultInstanceForType() {
      return com.power.proto3.PeopleInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.power.proto3.PeopleInfo build() {
      com.power.proto3.PeopleInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.power.proto3.PeopleInfo buildPartial() {
      com.power.proto3.PeopleInfo result = new com.power.proto3.PeopleInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.power.proto3.PeopleInfo result) {
      if (phoneBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.phone_ = phone_;
      } else {
        result.phone_ = phoneBuilder_.build();
      }
    }

    private void buildPartial0(com.power.proto3.PeopleInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.age_ = age_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.power.proto3.PeopleInfo) {
        return mergeFrom((com.power.proto3.PeopleInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.power.proto3.PeopleInfo other) {
      if (other == com.power.proto3.PeopleInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (phoneBuilder_ == null) {
        if (!other.phone_.isEmpty()) {
          if (phone_.isEmpty()) {
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePhoneIsMutable();
            phone_.addAll(other.phone_);
          }
          onChanged();
        }
      } else {
        if (!other.phone_.isEmpty()) {
          if (phoneBuilder_.isEmpty()) {
            phoneBuilder_.dispose();
            phoneBuilder_ = null;
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000004);
            phoneBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneFieldBuilder() : null;
          } else {
            phoneBuilder_.addAllMessages(other.phone_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              age_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.power.proto3.PeopleInfo.Phone m =
                  input.readMessage(
                      com.power.proto3.PeopleInfo.Phone.parser(),
                      extensionRegistry);
              if (phoneBuilder_ == null) {
                ensurePhoneIsMutable();
                phone_.add(m);
              } else {
                phoneBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      bitField0_ = (bitField0_ & ~0x00000002);
      age_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.power.proto3.PeopleInfo.Phone> phone_ =
      java.util.Collections.emptyList();
    private void ensurePhoneIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        phone_ = new java.util.ArrayList<com.power.proto3.PeopleInfo.Phone>(phone_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.power.proto3.PeopleInfo.Phone, com.power.proto3.PeopleInfo.Phone.Builder, com.power.proto3.PeopleInfo.PhoneOrBuilder> phoneBuilder_;

    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public java.util.List<com.power.proto3.PeopleInfo.Phone> getPhoneList() {
      if (phoneBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phone_);
      } else {
        return phoneBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public int getPhoneCount() {
      if (phoneBuilder_ == null) {
        return phone_.size();
      } else {
        return phoneBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public com.power.proto3.PeopleInfo.Phone getPhone(int index) {
      if (phoneBuilder_ == null) {
        return phone_.get(index);
      } else {
        return phoneBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder setPhone(
        int index, com.power.proto3.PeopleInfo.Phone value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.set(index, value);
        onChanged();
      } else {
        phoneBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder setPhone(
        int index, com.power.proto3.PeopleInfo.Phone.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder addPhone(com.power.proto3.PeopleInfo.Phone value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(value);
        onChanged();
      } else {
        phoneBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder addPhone(
        int index, com.power.proto3.PeopleInfo.Phone value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(index, value);
        onChanged();
      } else {
        phoneBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder addPhone(
        com.power.proto3.PeopleInfo.Phone.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.add(builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder addPhone(
        int index, com.power.proto3.PeopleInfo.Phone.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder addAllPhone(
        java.lang.Iterable<? extends com.power.proto3.PeopleInfo.Phone> values) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phone_);
        onChanged();
      } else {
        phoneBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder clearPhone() {
      if (phoneBuilder_ == null) {
        phone_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        phoneBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public Builder removePhone(int index) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.remove(index);
        onChanged();
      } else {
        phoneBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public com.power.proto3.PeopleInfo.Phone.Builder getPhoneBuilder(
        int index) {
      return getPhoneFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public com.power.proto3.PeopleInfo.PhoneOrBuilder getPhoneOrBuilder(
        int index) {
      if (phoneBuilder_ == null) {
        return phone_.get(index);  } else {
        return phoneBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public java.util.List<? extends com.power.proto3.PeopleInfo.PhoneOrBuilder> 
         getPhoneOrBuilderList() {
      if (phoneBuilder_ != null) {
        return phoneBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phone_);
      }
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public com.power.proto3.PeopleInfo.Phone.Builder addPhoneBuilder() {
      return getPhoneFieldBuilder().addBuilder(
          com.power.proto3.PeopleInfo.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public com.power.proto3.PeopleInfo.Phone.Builder addPhoneBuilder(
        int index) {
      return getPhoneFieldBuilder().addBuilder(
          index, com.power.proto3.PeopleInfo.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
     */
    public java.util.List<com.power.proto3.PeopleInfo.Phone.Builder> 
         getPhoneBuilderList() {
      return getPhoneFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.power.proto3.PeopleInfo.Phone, com.power.proto3.PeopleInfo.Phone.Builder, com.power.proto3.PeopleInfo.PhoneOrBuilder> 
        getPhoneFieldBuilder() {
      if (phoneBuilder_ == null) {
        phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.power.proto3.PeopleInfo.Phone, com.power.proto3.PeopleInfo.Phone.Builder, com.power.proto3.PeopleInfo.PhoneOrBuilder>(
                phone_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        phone_ = null;
      }
      return phoneBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto3.PeopleInfo)
  }

  // @@protoc_insertion_point(class_scope:proto3.PeopleInfo)
  private static final com.power.proto3.PeopleInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.power.proto3.PeopleInfo();
  }

  public static com.power.proto3.PeopleInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeopleInfo>
      PARSER = new com.google.protobuf.AbstractParser<PeopleInfo>() {
    @java.lang.Override
    public PeopleInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PeopleInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeopleInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.power.proto3.PeopleInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

