// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/contacts.proto

package com.power.proto3;

public interface PeopleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.PeopleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  java.util.List<com.power.proto3.PeopleInfo.Phone> 
      getPhoneList();
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  com.power.proto3.PeopleInfo.Phone getPhone(int index);
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  java.util.List<? extends com.power.proto3.PeopleInfo.PhoneOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  com.power.proto3.PeopleInfo.PhoneOrBuilder getPhoneOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Any data = 4;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.google.protobuf.Any data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.Any getData();
  /**
   * <code>.google.protobuf.Any data = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getDataOrBuilder();

  /**
   * <pre>
   *    repeated string qq = 5;
   * </pre>
   *
   * <code>string qq = 5;</code>
   * @return Whether the qq field is set.
   */
  boolean hasQq();
  /**
   * <pre>
   *    repeated string qq = 5;
   * </pre>
   *
   * <code>string qq = 5;</code>
   * @return The qq.
   */
  java.lang.String getQq();
  /**
   * <pre>
   *    repeated string qq = 5;
   * </pre>
   *
   * <code>string qq = 5;</code>
   * @return The bytes for qq.
   */
  com.google.protobuf.ByteString
      getQqBytes();

  /**
   * <code>string wechat = 6;</code>
   * @return Whether the wechat field is set.
   */
  boolean hasWechat();
  /**
   * <code>string wechat = 6;</code>
   * @return The wechat.
   */
  java.lang.String getWechat();
  /**
   * <code>string wechat = 6;</code>
   * @return The bytes for wechat.
   */
  com.google.protobuf.ByteString
      getWechatBytes();

  /**
   * <pre>
   * key:除了 float bytes 之外的任意标量类型
   *  repeated map&lt;string, string&gt; remark = 7;
   * 无序
   * </pre>
   *
   * <code>map&lt;string, string&gt; remark = 7;</code>
   */
  int getRemarkCount();
  /**
   * <pre>
   * key:除了 float bytes 之外的任意标量类型
   *  repeated map&lt;string, string&gt; remark = 7;
   * 无序
   * </pre>
   *
   * <code>map&lt;string, string&gt; remark = 7;</code>
   */
  boolean containsRemark(
      java.lang.String key);
  /**
   * Use {@link #getRemarkMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getRemark();
  /**
   * <pre>
   * key:除了 float bytes 之外的任意标量类型
   *  repeated map&lt;string, string&gt; remark = 7;
   * 无序
   * </pre>
   *
   * <code>map&lt;string, string&gt; remark = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getRemarkMap();
  /**
   * <pre>
   * key:除了 float bytes 之外的任意标量类型
   *  repeated map&lt;string, string&gt; remark = 7;
   * 无序
   * </pre>
   *
   * <code>map&lt;string, string&gt; remark = 7;</code>
   */
  /* nullable */
java.lang.String getRemarkOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * key:除了 float bytes 之外的任意标量类型
   *  repeated map&lt;string, string&gt; remark = 7;
   * 无序
   * </pre>
   *
   * <code>map&lt;string, string&gt; remark = 7;</code>
   */
  java.lang.String getRemarkOrThrow(
      java.lang.String key);

  public com.power.proto3.PeopleInfo.OtherContactCase getOtherContactCase();
}
