// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/contacts.proto

package com.power.proto3;

public interface PeopleInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.PeopleInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  java.util.List<com.power.proto3.PeopleInfo.Phone> 
      getPhoneList();
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  com.power.proto3.PeopleInfo.Phone getPhone(int index);
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  java.util.List<? extends com.power.proto3.PeopleInfo.PhoneOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .proto3.PeopleInfo.Phone phone = 3;</code>
   */
  com.power.proto3.PeopleInfo.PhoneOrBuilder getPhoneOrBuilder(
      int index);
}
